version: '3'

services:
  server:
    image: node:16.16.0
    container_name: server
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "yarn install && node server.js"
    restart: always
