name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-18.04
    env:
      HTTP_PORT: 5100
      HTTPS_PORT: 5300
      DATABASE: mongodb+srv://admin:abc-company@cluster0.qifvf.mongodb.net/abc-company?retryWrites=true&w=majority
      DATABASE_DEBUG: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Set up nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
